// The route map. EVERY route the handoff describes is registered here already,
// each pointing at a folder under `src/screens/`.
//
// ─────────────────────────────────────────────────────────────────────────────
//  DO NOT EDIT THIS FILE TO BUILD A SCREEN.
//
//  It exists so the wave-2 screen agents can each replace exactly ONE folder
//  under `src/screens/` in parallel, with no two of them touching the same
//  file. If you are implementing a screen, change only
//  `src/screens/<Name>/index.tsx` (and files you add inside that folder).
//  Adding a genuinely new route is the only reason to come back here.
// ─────────────────────────────────────────────────────────────────────────────
//
// The URL is the source of truth for navigation (CLAUDE.md › Frontend
// conventions). Nothing about "which page am I on" belongs in Zustand;
// intra-screen selection (active tab, expanded row) goes in query params.

import { createBrowserRouter, Navigate } from "react-router-dom";

import AppLayout from "./screens/AppLayout";
import AuthScreen from "./screens/Auth";
import ClaudeScreen from "./screens/Claude";
import IntegrationsScreen from "./screens/Integrations";
import LandingScreen from "./screens/Landing";
import OverviewScreen from "./screens/Overview";
import ProjectDetailScreen from "./screens/ProjectDetail";
import ProjectsScreen from "./screens/Projects";
import SettingsScreen from "./screens/Settings";
import TicketsScreen from "./screens/Tickets";
import UsersScreen from "./screens/Users";

export const router = createBrowserRouter([
  // Marketing landing view — no app shell.
  { path: "/", element: <LandingScreen /> },

  // The app shell wraps every /app page.
  {
    path: "/app",
    element: <AppLayout />,
    children: [
      { index: true, element: <OverviewScreen /> },
      { path: "projects", element: <ProjectsScreen /> },
      { path: "projects/:projectId", element: <ProjectDetailScreen /> },
      { path: "tickets", element: <TicketsScreen /> },
      { path: "claude", element: <ClaudeScreen /> },
      { path: "auth", element: <AuthScreen /> },
      { path: "users", element: <UsersScreen /> },
      { path: "integrations", element: <IntegrationsScreen /> },
      { path: "settings", element: <SettingsScreen /> },
    ],
  },

  // Anything else falls back to the landing view.
  { path: "*", element: <Navigate to="/" replace /> },
]);
